sudo: required
services:
 - docker

before_install:
 - docker build -t bpladna81/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run bpladna81/react-test npm test -- --coverage

after_success:
 - docker build -t bpladna81/multi-client ./client
 - docker build -t bpladna81/multi-nginx ./nginx
 - docker build -t bpladna81/multi-server ./server
 - docker build -t bpladna81/multi-worker ./worker
# Log in to the Docker CLI
 - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
#
# Take thOSE images and push them to Docker hub 
 - docker push bpladna81/multi-client
 - docker push bpladna81/multi-nginx
 - docker push bpladna81/multi-server
 - docker push bpladna81/multi-worker
